server:
  port: 8201
elasticsearch-client:
    hosts: http://xxx.xxx.xxx.xxx:9200
module-name: search
spring:
  redis:
    host: xxx.xxx.xxx.xxx
    password: xxxx
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: datasource
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/xxx?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: xxxx
    password: xxxx
  zipkin:
    base-url: http://xxx.xxx.xxx.xxx:9411
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
  application:
    name: search
  cloud:
    nacos:
      discovery:
        server-addr: xxx.xxx.xxx.xxx:8848
#logging:
#  level:
#    springfox.documentation.spring.web: DEBUG
xxl:
  job:
    admin:
      addresses: http://xxx.xxx.xxx.xxx:8120/xxl-job-admin
    accessToken: default_token
    executor:
      port: 9916
      appname: demo-service-impl
      logpath: /data/applogs/xxl-job/jobhandler
global-exception-handler:
  enabled: true