server:
  port: 1688
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: datasource

    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/xxxx?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: xxxx
    password: xxxx
  zipkin:
    base-url: http://xxx.xxx.xxx.xxx:9411
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
  application:
    name: chat
  cloud:
    nacos:
      discovery:
        server-addr: xxx.xxx.xxx.xxx:8848
module-name: chat