server:
  port: 8200
spring:
  redis:
    host: xxx.xxx.xxx.xxx
  application:
    name: gateway
  zipkin:
    base-url: http://xxx.xxx.xxx.xxx:9411
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: datasource
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/xxxx?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: xxxx
    password: xxxx
  cloud:
    loadbalancer:
      enabled: true
    nacos:
      discovery:
        server-addr: xxx.xxx.xxx.xxx:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: websocket
          uri: ws://xxx.xxx.xxx.xxx:xx
          predicates:
            - Path=/ljl/bilibili/chat
        - id: route1
          uri: http://xxx.xxx.xxx.xxx:xx
          predicates:
            - Path=/changeNoticeStatus/**,/getNotice/**
        - id: route2
          uri: http://xxx.xxx.xxx.xxx:xx
          predicates:
            - Path=/ensemble/**,/follow/**,/selfCenter/**,/userInfo/**
        - id: route3
          uri: http://xxx.xxx.xxx.xxx:xx
          predicates:
            - Path=/collect/**,/comment/**,/danmaku/**,/videoToEnsemble/**,/like/**,/createCenter/**,/play/**
        - id: route4
          uri: http://xxx.xxx.xxx.xxx:xx
          predicates:
            - Path=/chat/**
        - id : route5
          uri: http://xxx.xxx.xxx.xxx:xx
          predicates:
            - Path=/search/**
        - id: user-center
          uri: http://xxx.xxx.xxx.xxx:xx
          predicates:
            - Path=/user-center/**
          filters:
            - RewritePath=/user-center/(?<segment>.*), /$\{segment}

        - id: notice
          uri: http://xxx.xxx.xxx.xxx:xx
          predicates:
            - Path=/notice/**
          filters:
            - RewritePath=/notice/(?<segment>.*), /$\{segment}
        - id: video
          uri: http://xxx.xxx.xxx.xxx:xx
          predicates:
            - Path=/video/**
          filters:
            - RewritePath=/video/(?<segment>.*), /$\{segment}
        - id: search
          uri: http://xxx.xxx.xxx.xxx:xx
          predicates:
            - Path=/searchs/**
          filters:
            - RewritePath=/searchs/(?<segment>.*), /$\{segment}
        - id: chat
          uri: http://xxx.xxx.xxx.xxx:xx
          predicates:
            - Path=/chats/**
          filters:
            - RewritePath=/chats/(?<segment>.*), /$\{segment}
        - id: mock
          uri: http://xxx.xxx.xxx.xxx:xx
          predicates:
            - Path=/mock/**
          filters:
            - RewritePath=/mock/(?<segment>.*), /$\{segment}




module-name: gateway
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
global-exception-handler:
  enabled: false