server:
  port: 10201
spring:
  application:
    name: video
  zipkin:
    base-url: http://xxx.xxx.xxx.xxx:9411
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1 # sleuth 日志记录采样率，1为100%，默认为0.1即10%
  cloud:
    nacos:
      discovery:
        server-addr: xxx.xxx.xxx.xxx:8848
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      location: var/temp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    hikari:
#      max-lifetime: 2520000  7 小时
#      idle-timeout: 21600000   6 小时
#      validation-timeout: 5000  5 秒
    name: datasource
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/xxx?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: xxxx
    password: xxxx

minio:
  url: http://xxx.xxx.xxx.xxx:9000
  access.name: xxxx
  access.secret: xxxx
  bucket.name: xxxx
rocketmq:
  name-server: xxx.xxx.xxx.xxx:9876
  producer:
    group: producer
module-name: video
global-exception-handler:
  enabled: true

#logging:
#  level:
#    root: debug





