server:
  port: 3000
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  zipkin:
    base-url: http://xxx.xxx.xxx.xxx:9411
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: datasource
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/xxx?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: xxxx
    password: xxxx
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: xxx.xxx.xxx.xxx:8848
        register-enabled: true
module-name: user_center
minio:
  url: http://xxx.xxx.xxx.xxx:9000
  access.name: xxxx
  access.secret: xxxx
  bucket.name: user-cover
global-exception-handler:
  enabled: true
#logging:
#  level:
#    springfox.documentation.spring.web: DEBUG
#    spring.web: DEBUG


